version: "3.7"

networks:
  testovoye-network:
    name: testovoye-network

services:
  postgres:
    image: postgres:11
    container_name: testovoye-postgres
    environment: 
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    volumes:
       - postgres-storage:/data/postgres
    networks:
      - testovoye-network
    ports:
      - 5435:${PSQL_PORT}
    restart: always
    hostname: ${PSQL_HOST}
  testovoye-app:
    container_name: testovoye-app
    networks:
      - testovoye-network
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

volumes:
  postgres-storage: