version: "3.7"

volumes:
  postgres-storage:

networks:
  crud-network:
    name: testovoye-network

services:
  postgres:
    image: postgres:11
    container_name: testovoye-postgres
    environment: 
      - POSTGRES_USER=testovoye
      - POSTGRES_PASSWORD=testovoye
      - PGDATA=/data/postgres
    volumes:
       - postgres-storage:/data/postgres
    networks:
      crud-network:
    ports:
      - "5435:5432"
    hostname: testovoye-postgres
    restart: always

