version: "3.7"

volumes:
  postgres-storage:

networks:
  checker-network:
    name: events-network

services:
  postgres:
    image: postgres:11
    container_name: events-postgres
    environment: 
      - POSTGRES_USER=events
      - POSTGRES_PASSWORD=events
      - PGDATA=/data/postgres
    volumes:
       - postgres-storage:/data/postgres
    networks:
      checker-network:
    ports:
      - "5435:5432"
    hostname: events-postgres
    restart: always
  adminer:
    image: michalhosna/adminer
    container_name: events-adminer
    environment:
      - ADMINER_SERVER=events-postgres:5432
      - ADMINER_DRIVER=pgsql
    networks:
      checker-network:
    ports:
      - "8092:8080"
    hostname: events
    restart: always

